version: "3"
services:
  php:
    container_name: "apache"
    image: php:8.1.16-apache
    volumes:
     - ./arquivos/:/var/www/html/
    ports:
     - 8080:80      
  db:
    image: mariadb:10.5
    container_name: "mariadb"
    restart: always
    environment:
    - MARIADB_USER=root
    - MARIADB_ROOT_PASSWORD=123
  adminer:
    image: adminer:4.8.1
    container_name: "adm_cea"
    restart: always
    ports:
      - 81:8080